theme = "catppuccin_mocha"

[editor]
cursorline  = true
line-number = "relative"
mouse       = false
color-modes = true

[keys.normal]
ret = ":w"
space = { c = ":bc" }

[editor.lsp]
display-messages = true

[editor.file-picker]
git-ignore = true
hidden     = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.statusline]
center = ["file-name"]
left = ["mode", "spinner"]
right = [
  "diagnostics",
  "selections",
  "position",
  "file-encoding",
  "file-line-ending",
  "file-type",
]
