[[language]]
file-types      = ["js", "mjs", "cjs", "ts"]
language-server = { command = "efm-langserver" }
name            = "javascript"
auto-format     = true
roots           = [".git"]

[[language]]
name            = "markdown"
scope           = "source.md"
injection-regex = "md|markdown"
file-types      = ["md"]
roots           = [".marksman.toml"]
language-server = { command = "marksman", args = ["server"] }
indent          = { tab-width = 2, unit = "  " }

[[language]]
name            = "python"
roots           = ["pyproject.toml", "setup.py", "."]
language-server = { command = "pyright-langserver", args = ["--stdio"] }
config          = {}
