version: 2
root-markers:
  - .git/
lint-debounce: 1s

tools:
  eslint: &eslint
    lint-command: 'eslint_d -f unix --stdin --stdin-filename=${INPUT}'
    lint-ignore-exit-code: true
    lint-stdin: true

  eslint-format: &eslint-format
    format-command: 'eslint_d --stdin --fix-to-stdout --stdin-filename=${INPUT}'
    format-stdin: true
    lint-formats:
      - "%f:%l:%c: %m"

languages:
  javascript:
    - <<: *eslint
    - <<: *eslint-format

